import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import {sections,sources} from '../dist/data.js';
const code=fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8').replace(/import \{sections,sources\} from '\.\/data\.js(?:\?[^']*)?';/,'');
function harness(){const nodes=new Map();let saved='{}';const document={querySelector(id){if(!nodes.has(id))nodes.set(id,{value:'',checked:false,innerHTML:'',addEventListener(){},focus(){}});return nodes.get(id);},querySelectorAll(){return []}};const c=vm.createContext({sections,sources,document,localStorage:{getItem:()=>saved,setItem:(_,v)=>saved=v},setTimeout:fn=>fn(),confirm:()=>true,console});vm.runInContext(code,c);return {run:s=>vm.runInContext(s,c),node:id=>document.querySelector(id)};}
test('Every figure exists and every marker lies within its image',()=>{let targets=0;for(const s of sections){assert(s.facts.length);for(const v of s.views){assert(fs.existsSync(new URL('../dist/assets/'+v.src,import.meta.url)));assert.equal(v.size.length,2);for(const t of v.targets){targets++;assert(t.name&&t.teach);assert(t.x>=0&&t.x<=100&&t.y>=0&&t.y<=100);if(t.pin)assert(t.pin.every(n=>n>=0&&n<=100));}}for(const q of s.facts){assert(q.options.includes(q.a));assert.equal(new Set(q.options).size,q.options.length);}}assert(targets>=80);});
test('Every typed target and alias grades correctly; repeated submission cannot inflate score',()=>{const h=harness();for(const sec of sections){const bank=h.run(`bank(sections.find(s=>s.id==='${sec.id}'),'typed')`);for(const q of bank.filter(q=>q.type==='typed')){for(const name of [q.a,...(q.aliases||[])]){h.run(`state.session={questions:[${JSON.stringify(q)}],index:0,records:[],hint:false,answered:false};state.mode='practice';answer(${JSON.stringify(' '+name.toUpperCase()+' ')});`);assert(h.run('state.session.feedback.correct'));h.run("answer('not the answer')");assert.equal(h.run('state.session.records.length'),1);}}}});
test('Location practice accepts only the correct marker and hint use remains assisted',()=>{const h=harness();h.run("state.session={questions:bank(sections[1],'locate'),index:0,records:[],hint:true,answered:false};state.mode='practice';answer(0)");assert(h.run('state.session.feedback.correct'));assert(h.run('state.session.feedback.assisted'));assert.equal(h.run('state.stats[state.session.questions[0].id].correct'),0);h.run("state.session.index=1;state.session.answered=false;state.session.hint=false;answer(0)");assert.equal(h.run('state.session.feedback.correct'),false);});
test('Standard 40-question exam balances all 8 sections and excludes extensions',()=>{const h=harness();h.node('#exam-length').value='40';h.node('#extensions').checked=false;h.run('start(true)');assert.equal(h.run('state.session.questions.length'),40);for(const s of sections)assert.equal(h.run(`state.session.questions.filter(q=>q.section==='${s.id}').length`),5);assert.equal(h.run("state.session.questions.filter(q=>q.q.startsWith('Extension:')||q.view==='meninges').length"),0);h.run('answer(state.session.questions[0].type===\'locate\'?state.session.questions[0].target:state.session.questions[0].a)');assert(h.node('#app').innerHTML.includes('Answer recorded.'));assert(!h.node('#app').innerHTML.includes('class="feedback good"'));});
test('Complete bank, practice limits, mistakes, skipping and results',()=>{const h=harness();h.node('#exam-length').value='all';h.node('#extensions').checked=true;h.run('start(true)');const expected=h.run('sections.reduce((n,s)=>n+bank(s).length,0)');assert.equal(h.run('state.session.questions.length'),expected);assert.equal(h.run('new Set(state.session.questions.map(q=>q.id)).size'),expected);h.run("state.session=null;state.section='planes'");h.node('#format').value='choice';h.node('#scope').value='planes';h.node('#practice-length').value='10';h.run('start(false)');assert.equal(h.run('state.session.questions.length'),4);h.run("answer('Skipped');state.session.index++;state.session.answered=false;answer('wrong')");assert.equal(h.run('state.session.records.filter(r=>r.correct).length'),0);const html=h.run('results()');assert(html.includes('0 of 2'));assert(html.includes('Practice missed & assisted (2)'));});
test('Storage denial and corrupt saved preferences do not stop the app',()=>{const document={querySelector:()=>({innerHTML:'',addEventListener(){}}),querySelectorAll:()=>[]};const c=vm.createContext({sections,sources,document,localStorage:{getItem(){throw Error('blocked')},setItem(){throw Error('blocked')}},setTimeout:()=>{},console});vm.runInContext(code,c);vm.runInContext('persist()',c);assert(vm.runInContext('state.storageError',c));});
test('Typed drafts survive hint and zoom renders, and review identifies the original diagram',()=>{const h=harness();h.run("state.session={questions:bank(sections.find(s=>s.id==='planes'),'typed','planes'),index:0,records:[],hint:false,answered:false,draft:'coronal plane'};state.mode='practice';render()");assert(h.node('#app').innerHTML.includes('value="coronal plane"'));h.run('state.zoom=1.5;state.session.hint=true;render()');assert(h.node('#app').innerHTML.includes('value="coronal plane"'));h.run("answer('wrong');state.mode='results';render()");assert(h.node('#app').innerHTML.includes('class="review-figure"'));assert(h.node('#app').innerHTML.includes('Four ways to section the body'));assert(h.node('#app').innerHTML.includes('assets/planes.png'));});
